server:
  port: 8888

team:
  name: "Web2班"
  leader: "lyc"
  age: 6
  phone: 13372024350
  "createTime": "2025-09-10"

#teacher:
#  name: "mqxu"


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB